### ISSUE TITLE
https path not found

### ISSUE THREAD

**Issue by mark-sherwin** [jimmyGALLAND/redpill-ext#8]
Hi Jimmy. I don't know if I'm logging this issue correctly or not.
I'm trying to build xpenology in a VM on ESXi.
The build I'm using is tinycore-redpill.v0.4.6 by Tim Myers
When the command ./rploader.sh build broadwellnk-7.0.1-42218 auto is run the script references 
 https://github.com/jimmyGALLAND/redpill-ext/raw/master/redpill-boot-wait/recipes/universal.json but fails as the path is invalid..
Is this something you can assist with..
Thank you

**Comment by mark-sherwin** [comment]
Apologies Jimmy, I've found a solution 
./rploader.sh fullupgrade
will pull all current components.. I say this not for your benefit, I'm sure you are aware of this but for others.

**Comment by jimmyGALLAND** [comment]
Hello
I don't longer propose redpill-boot-wait on this git in order to avoid few git with a thing is already proposed by pocopico (The 
tinycore-redpill's author)

I invite you to use the following repository instead
https://github.com/pocopico/rp-ext/blob/main/redpill-boot-wait/rpext-index.json
or update your tinycore-redpill image builder.
https://github.com/pocopico/tinycore-redpill/tree/main
version 0.8.0 on main branch
or 9.0.2 on develop branch


If you want, have a look at the powerful fbelavenuta's tool
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha3

**Comment by Kepete** [comment]
For anyone else finding this issue in the future.

I tried running what @mark-sherwin  suggested `./rploader.sh fullupgrade` as well as `./rploader.sh update` but still got the 404 error. 
I had to also run `./rploader.sh clean now` and start all over again from the beginning for the fullupgrade to take affect.

**Comment by murph146** [comment]
> 

Ran into the same issue and running ./rploader.sh clean now fixed the issue as well. If i can ask a dumb question, why does running this command and that start the process over fix the issue?
